### PR TITLE
Add localaddress setting to bind to a network address

### PR DESCRIPTION
**Pull request by brutuscat**
Node's net package allows to pass a localAddress option that binds the
socket connection to an specific address of the network interface.
Without it, the OS choose one (usually the firs address of the
interface).

This commit reads this option `localaddress` from the local storage
settings (even tough it does not ask for it in the setup) and passes
it into all the invocations that potentially opens a connection.

In order for this to work the connection to the server was forced
to always use the websocket transport, because otherwise the socket.io
client will first try using the polling before upgrading to a websocket
connection transport, which internally uses a XMLHttpRequest for the
polling and the socket-io options never reach that "deep" in the
module dependencies.

### CODE REVIEW

**Comment by ADumaine** [comment]
I am not sure why this is needed.  Please explain.  What is the intended purpose?

**Comment by brutuscat** [comment]
@ADumaine this is obviously needed so node operators can:

- selectively choose which address disclose (e.g. use) to the Secure Node Server.
- add the ability to run multiple nodes from the same server with multiple ip addresses.

The use case is similar to zend `externalip` option. See https://github.com/bitcoin/bitcoin/issues/15

**Comment by ADumaine** [comment]
Running multiple nodes and trackers on the same system goes against the original intent of building a global network of resilient secure nodes independent of each other.  The requirement of an IP address was introduced to help ensure that each node would run on its own server and have the resources to create and process a shielded transaction at any time.  Overlapping shared resources on the same server may be beneficial to the node operator but does not help the overall node network or upcoming applications that may rely on the nodes.   

Although it is technically possible to run concurrent nodes this way, it is not a configuration that was intended to be compensated. This PR can remain here for reference in case there comes a time for some sort of high availability configuration, but will not be incorporated at this time.

**Comment by brutuscat** [comment]
@ADumaine your answer does not sounds very "open"... I disagree. 

In the new world of IPv6 where anybody have have thousands of ip addresses why I can not choose which address I want to bind to which service?

Also you say that u do now want to compensate running multiple trackers on the same machine, well what about VPS? A vps is a shared computing resource, which effectively is (although much less efficient) multiple nodes in the same machine. Everybody is using VPS nonetheless. 

I do hope you reopen this PR and I will be happy to accomodate any other change you want. Like I could also modify the setup.js so if we detect that the zen.conf is using the `externalip` setting, take the address from there into the `localaddress` local storage file.

**Comment by ADumaine** [comment]
It is not a matter of openness.  It is more matters of contributing to the network and fairness.

With a VPS provider there is a 3rd party involved managing the resources.  If an operator can set up as many nodes on a server without limitation, what is to keep him from oversubscribing and creating 6 on resources that would otherwise support 1 virtual node server?  Does that provide proper service to the network or is it designed to maximize operator profit?  Is it fair to other operators?

This looks like it would also allow every operator to double or triple the nodes running on every current server without any real benefit to the network.  And it would dilute the allocation for all nodes.

There are over 6400 nodes running that have not needed the ability to assign multiple IP addresses to one node server.   I am still not convinced of the need for this from a secure node network perspective.

**Comment by brutuscat** [comment]
@ADumaine 

> what is to keep him from oversubscribing and creating 6 on resources that would otherwise support 1 virtual node server?

The computing-constrained "challenge" computation. 

> Does that provide proper service to the network or is it designed to maximize operator profit? Is it fair to other operators?

That is a question for a provider of VPS services I guess... Some of them are ok with it some not.

> This looks like it would also allow every operator to double or triple the nodes running on every current server without any real benefit to the network. And it would dilute the allocation for all nodes.

I agree, but it is a bit naive to think that people still only use real "metal" computers... There is VMs and docker. Nowadays everything is virtualized.

The multiple IPv6 address point is still on the table too.

**Comment by tarrenj** [comment]
@brutuscat Can you think of a way to merge this while still working to keep nodes decentralized?  Our fear is that merging this would decrease the barrier for entry to the point that it would become feasible for someone to host enough nodes that they'd be able to control a large portion of the network.

I agree that this feature would be nice to have, but is it worth dropping the requirement that each node is run independently?  I don't think it is.

Thoughts?

**Pull request closed without merging**
